# Generated by Django 2.1.4 on 2019-03-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_imagequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepoll',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.ImageQuestion'),
        ),
    ]
