# Generated by Django 2.1.4 on 2019-04-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_auto_20190418_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='selfieimages',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='user',
        ),
        migrations.DeleteModel(
            name='SelfieImages',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
