# Generated by Django 2.1.4 on 2019-05-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0020_mymoments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoments',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
