# Generated by Django 2.1.4 on 2019-05-02 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_auto_20190502_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymoments',
            old_name='user',
            new_name='author',
        ),
    ]
