# Generated by Django 2.1.4 on 2019-05-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_auto_20190502_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoments',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
