# Generated by Django 2.1.4 on 2019-05-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0023_auto_20190502_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoments',
            name='author',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
