# Generated by Django 2.1.4 on 2019-05-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0024_auto_20190502_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoments',
            name='crucial',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mymoments',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
